// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECg-rU_zV0QtcnQGrK1ksxCFjxyFl0R8',
    appId: '1:125420512259:web:662d7f7ffea43095201a36',
    messagingSenderId: '125420512259',
    projectId: 'obd2-ace36',
    authDomain: 'obd2-ace36.firebaseapp.com',
    storageBucket: 'obd2-ace36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1yPWel6KHRSYWl3Zy2zHMWJzRkPn-H0',
    appId: '1:125420512259:android:75225562c73a6565201a36',
    messagingSenderId: '125420512259',
    projectId: 'obd2-ace36',
    storageBucket: 'obd2-ace36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiACIDlMaHA4PJvsNvqY5Xh14FKBrG6zU',
    appId: '1:605732491601:ios:a5d545b5fea6cb2d7bc370',
    messagingSenderId: '605732491601',
    projectId: 'obd2-5a7b1',
    databaseURL: 'https://obd2-5a7b1-default-rtdb.firebaseio.com',
    storageBucket: 'obd2-5a7b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiACIDlMaHA4PJvsNvqY5Xh14FKBrG6zU',
    appId: '1:605732491601:ios:a5d545b5fea6cb2d7bc370',
    messagingSenderId: '605732491601',
    projectId: 'obd2-5a7b1',
    databaseURL: 'https://obd2-5a7b1-default-rtdb.firebaseio.com',
    storageBucket: 'obd2-5a7b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTIVo51M9vPJS3o6UtwGKkc8hEnRQZ-zA',
    appId: '1:605732491601:web:131bc437fd06ea617bc370',
    messagingSenderId: '605732491601',
    projectId: 'obd2-5a7b1',
    authDomain: 'obd2-5a7b1.firebaseapp.com',
    databaseURL: 'https://obd2-5a7b1-default-rtdb.firebaseio.com',
    storageBucket: 'obd2-5a7b1.firebasestorage.app',
  );
}